### ISSUE TITLE
Issue formatting the table

### ISSUE THREAD

**Issue by riannazandbelt** [riannazandbelt/saas-website#1]
Hi @mackenzierose,

As I was formatting my SAAS website, I was encountering an issue when trying to format the table on my tour.html page. I know my code is incorrect, but I was wondering how I could have the content under the integrations part of the table be in a column format. I've included a screenshot of my SAAS website that I used in Interaction Design to better explain what I'm trying to achieve.

Thanks,
Rianna
<img width="374" alt="Screen Shot 2020-04-08 at 9 01 02 AM" src="https://user-images.githubusercontent.com/55094049/78787509-738edb80-7978-11ea-8225-ee06570e83e4.png">

**Comment by MacKenzieRose** [comment]
Hi,

There are two approaches that come to mind:

1. Add paragraphs: Less semantically appropriate, but would require less coding:
<img width="689" alt="Screen Shot 2020-04-08 at 10 18 04 AM" src="https://user-images.githubusercontent.com/19557909/78796178-fb2e1780-7983-11ea-8f41-0283e67b86ed.png">

Looks like this:
![Screen Shot 2020-04-08 at 10 16 39 AM](https://user-images.githubusercontent.com/19557909/78796384-392b3b80-7984-11ea-9dc7-19098c19fb0a.png)




2. Nest tables: More semantically appropriate, but seems like a lot more work:

<img width="660" alt="Screen Shot 2020-04-08 at 10 28 45 AM" src="https://user-images.githubusercontent.com/19557909/78796225-0aad6080-7984-11ea-91ab-892bf95b1103.png">

Looks like this:

![Screen Shot 2020-04-08 at 10 28 51 AM](https://user-images.githubusercontent.com/19557909/78796316-257fd500-7984-11ea-8493-f88e761a20e8.png)


Let me know if that helps. :)
MacKenzie
